name: structure_example
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  async: ^2.4.2
  mime: ^0.9.7
  http: ^0.12.2
  dio: ^3.0.10
  provider: ^4.3.2+1
  flutter_local_notifications: ^4.0.0
  url_launcher: ^5.7.10
  intl: ^0.16.1
  i18n: ^2.0.1
  yaml: ^2.2.1
  page_transition: ^1.1.6 
  flutter_cache_manager: ^2.1.0
  cached_network_image: ^2.2.0+1
  flutter_svg: ^0.19.0
  preload_page_view: ^0.1.4
  flutter_html: ^1.2.0
  google_sign_in: ^4.5.9
  flutter_facebook_login: ^3.0.0
  flushbar: ^1.10.4
  socket_io_client: ^0.9.12
  image_picker: ^0.6.7+4
  file_picker: ^2.1.6
  photo_view: ^0.10.3
  pull_to_refresh: 1.6.3
  firebase_messaging: ^7.0.3
  dotted_line: ^2.0.2
  carousel_slider: ^3.0.0

dev_dependencies:
  # build_runner: ^1.11.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/config/
    - assets/language/

  fonts:
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: Montserrat-ExtraBold
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
